regions = {'na': {'sandbox': 'advertising-api-test.amazon.com',
                  'prod': 'advertising-api.amazon.com',
                  'token_url': 'api.amazon.com/auth/o2/token'},
           'eu': {'sandbox': 'advertising-api-test.amazon.com',
                  'prod': 'advertising-api-eu.amazon.com',
                  'token_url': 'api.amazon.com/auth/o2/token'},
           'jp': {'sandbox': 'advertising-api-test.amazon.com',
                  'prod': 'advertising-api-fe.amazon.com',
                  'token_url': 'api.amazon.com/auth/o2/token'},
           }
